# Generated by Django 5.2.17 on 2026-09-16 11:14

from django.db import migrations, models
from django.db.models import Max


def backfill_from_activity(apps, schema_editor):
    """`last_login` was never written by the JWT sign-in (see
    accounts.presence), but every sign-in was audited. Fill last_login from
    the newest `login` row and last_seen_at from the newest row of any kind,
    for accounts that have nothing recorded yet."""
    User = apps.get_model("accounts", "User")
    ActivityLog = apps.get_model("core", "ActivityLog")
    logins = dict(
        ActivityLog.objects.filter(action="login", user__isnull=False)
        .values_list("user_id")
        .annotate(latest=Max("created_at"))
        .values_list("user_id", "latest")
    )
    seen = dict(
        ActivityLog.objects.filter(user__isnull=False)
        .values_list("user_id")
        .annotate(latest=Max("created_at"))
        .values_list("user_id", "latest")
    )
    for user in User.objects.filter(pk__in=set(logins) | set(seen)).iterator():
        fields = []
        if user.last_login is None and user.pk in logins:
            user.last_login = logins[user.pk]
            fields.append("last_login")
        if user.last_seen_at is None and user.pk in seen:
            user.last_seen_at = seen[user.pk]
            fields.append("last_seen_at")
        if fields:
            user.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_platform_invitation'),
        ('core', '0004_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_from_activity, migrations.RunPython.noop),
    ]
