# Generated by Django 5.2.17 on 2026-09-16 04:57

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_company_timezone'),
        ('website', '0003_registrationrequest_ownerinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.CharField(blank=True, choices=[('grocery', 'Grocery & food'), ('pharmacy', 'Pharmacy'), ('wholesale', 'Wholesale & distribution'), ('electronics', 'Electronics'), ('fashion', 'Fashion & clothing'), ('cosmetics', 'Cosmetics & perfume'), ('hardware', 'Hardware & building'), ('restaurant', 'Restaurant & café'), ('services', 'Services'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='website',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='website',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.site_upload_path),
        ),
        migrations.AddField(
            model_name='website',
            name='list_in_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.site_upload_path),
        ),
        migrations.AddField(
            model_name='website',
            name='map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='website',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=website.models.site_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_images', to='org.company')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.website')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
