# Generated by Django 5.2.17 on 2026-09-16 10:36

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_public_site_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_site_verification', models.CharField(blank=True, max_length=255)),
                ('bing_site_verification', models.CharField(blank=True, max_length=255)),
                ('analytics_id', models.CharField(blank=True, max_length=64)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to=website.models.seo_upload_path)),
                ('robots_extra', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO settings',
                'verbose_name_plural': 'SEO settings',
            },
        ),
        migrations.CreateModel(
            name='SeoPageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('both', 'Both')], default='both', max_length=4)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('noindex', models.BooleanField(default=False)),
                ('canonical', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path', 'language'],
                'constraints': [models.UniqueConstraint(fields=('path', 'language'), name='seo_override_path_language')],
            },
        ),
    ]
