# Generated by Django 5.2.17 on 2026-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_seo_settings_and_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='services',
            field=models.TextField(blank=True),
        ),
    ]
