# Generated by Django 5.2.17 on 2026-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_website_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformlead',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='platformlead',
            name='preferred_channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone call'), ('email', 'Email')], default='whatsapp', max_length=16),
        ),
        migrations.AlterField(
            model_name='platformlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
