# Generated by Django 5.2.17 on 2026-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_platformlead_phone_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='support_whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
