# Generated by Django 5.2.17 on 2026-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_seosettings_support_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformlead',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformlead',
            name='last_contact_channel',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='platformlead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformlead',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='last_contact_channel',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
