# Generated by Django 5.2.17 on 2026-09-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_follow_ups'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('path', models.CharField(max_length=200)),
                ('page_kind', models.CharField(choices=[('marketing', 'Marketing page'), ('public_site', 'Company public page'), ('directory', 'Public directory')], max_length=16)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('bot_visits', models.PositiveIntegerField(default=0)),
                ('referrers', models.JSONField(blank=True, default=dict)),
                ('devices', models.JSONField(blank=True, default=dict)),
                ('languages', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'page_kind'], name='dailystat_date_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'path'), name='daily_stat_date_path')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('page_kind', models.CharField(choices=[('marketing', 'Marketing page'), ('public_site', 'Company public page'), ('directory', 'Public directory')], max_length=16)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('referrer_host', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=8)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('visitor_hash', models.CharField(max_length=32)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='pagevisit_created_idx')],
            },
        ),
    ]
