# Generated by Django 5.2.17 on 2026-09-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_hot_table_indexes'),
        ('org', '0011_device'),
        ('sales', '0017_payment_store_credit'),
        ('website', '0010_dailypagestat_pagevisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='allow_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featuredproduct',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='accept_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='order_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PublicOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='new', max_length=12)),
                ('contact_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('delivery_mode', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=12)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('currency', models.CharField(max_length=8)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('visitor_hash', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_orders', to='org.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_orders', to='org.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_orders', to='sales.customer')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_order', to='sales.salesorder')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_orders', to='website.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='website.publicorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='publicorder',
            index=models.Index(fields=['company', 'status', 'created_at'], name='website_pub_company_5b2070_idx'),
        ),
    ]
