# Generated by Django 5.2.17 on 2026-09-19 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_device'),
        ('sales', '0018_bank_account_public'),
        ('website', '0012_push_and_notify_prefs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='PublicOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_bank_name', models.CharField(max_length=120)),
                ('reference_last4', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('proof', models.ImageField(blank=True, upload_to='order-proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('verifying', 'Verifying'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('fraud', 'Fraud')], default='verifying', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('visitor_hash', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.companybankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_order_payments', to='org.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='website.publicorder')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_claim', to='sales.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('visitor_hash', models.CharField(blank=True, max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_contacts', to='org.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.publicorderpayment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='publicorderpayment',
            constraint=models.UniqueConstraint(fields=('order', 'reference_last4'), name='one_claim_per_order_reference'),
        ),
        migrations.AddIndex(
            model_name='blockedcontact',
            index=models.Index(fields=['company', 'phone'], name='website_blo_company_3082d1_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedcontact',
            index=models.Index(fields=['company', 'visitor_hash'], name='website_blo_company_8cd4f8_idx'),
        ),
    ]
