# Generated by Django 5.2.17 on 2026-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_order_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorder',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
