# Generated by Django 5.2.17 on 2026-09-25 15:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0017_company_is_demo'),
        ('website', '0014_public_order_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorder',
            name='lookup_name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='publicorder',
            name='tracking_token',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publicorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('preparing', 'Preparing'), ('ready', 'Ready for pickup'), ('delivering', 'Out for delivery'), ('completed', 'Completed')], default='new', max_length=12),
        ),
        migrations.CreateModel(
            name='PublicOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('preparing', 'Preparing'), ('ready', 'Ready for pickup'), ('delivering', 'Out for delivery'), ('completed', 'Completed')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_order_events', to='org.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.publicorder')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
