# Generated by Django 5.2.17 on 2026-09-25 16:30

from django.db import migrations, models


def _phone_key(phone):
    arabic = str.maketrans("٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹", "01234567890123456789")
    digits = "".join(ch for ch in str(phone or "").translate(arabic) if ch.isdigit())
    return digits[-9:] if len(digits) >= 9 else ""


def backfill(apps, schema_editor):
    PublicOrder = apps.get_model("website", "PublicOrder")
    for order in PublicOrder.objects.exclude(phone="").iterator():
        key = _phone_key(order.phone)
        if key and order.lookup_phone != key:
            order.lookup_phone = key
            order.save(update_fields=["lookup_phone"])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_backfill_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicorder',
            name='lookup_phone',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
