# Generated by Django 5.2.17 on 2026-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_order_lookup_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformlead',
            name='lookup_name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platformlead',
            name='lookup_phone',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='platformlead',
            name='public_reference',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='lookup_company',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='lookup_name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='lookup_phone',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='public_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='public_reference',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
