# Generated by Django 5.2.17 on 2026-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_backfill_platform_request_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='pricing_default_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='pricing_show_compare',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='pricing_show_self_hosted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='pricing_template',
            field=models.CharField(choices=[('classic', 'Classic cards'), ('featured', 'Featured plan in the middle'), ('table', 'Comparison table'), ('compact', 'Compact list')], default='classic', max_length=16),
        ),
    ]
