# Generated by Django 5.2.17 on 2026-09-17 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_supplier_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='bill',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
