# Generated by Django 5.2.17 on 2026-09-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_costing_integrity_and_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
