# Generated by Django 5.0.14 on 2026-09-14 13:14

from django.conf import settings
from django.db import migrations, models


def backfill_numbers(apps, schema_editor):
    """Give every pre-existing note a sequential number per company in
    creation order, and leave the DocumentSequence counters positioned after
    the last one so new notes continue the run without gaps."""
    DocumentSequence = apps.get_model("core", "DocumentSequence")
    for model_name, doc_type in (("CreditNote", "credit_note"), ("DebitNote", "debit_note")):
        Model = apps.get_model("returns", model_name)
        counters = {}
        for note in Model.objects.order_by("company_id", "created_at", "id").iterator():
            counters[note.company_id] = counters.get(note.company_id, 0) + 1
            note.number = counters[note.company_id]
            note.save(update_fields=["number"])
        for company_id, last in counters.items():
            DocumentSequence.objects.update_or_create(
                company_id=company_id, doc_type=doc_type,
                defaults={"last_number": last},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_storemodeaccessexception'),
        ('purchasing', '0003_supplier_updated_at'),
        ('core', '0002_document_sequence'),
        ('returns', '0002_purchasereturnline_source_and_walkin_credit'),
        ('sales', '0005_customer_invoice_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_credit_note_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='debitnote',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_debit_note_number_per_company'),
        ),
    ]
