# Generated by Django 5.2.17 on 2026-09-17 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_costing_integrity_and_currency'),
        ('returns', '0003_note_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_lines', to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='written_off_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
