# Generated by Django 5.2.17 on 2026-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_costing_integrity_and_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
