# Generated by Django 5.0.14 on 2026-09-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptioninvoice_entitlement_granted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features_ar',
            field=models.TextField(blank=True, help_text='One feature per line.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='features_en',
            field=models.TextField(blank=True, help_text='One feature per line.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='tagline_ar',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='plan',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
