# Generated by Django 5.2.17 on 2026-09-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='planchangerequest',
            name='extra_delta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='planversion',
            name='addon_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='extra_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='kind',
            field=models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('addon', 'Add units'), ('addon_remove', 'Remove units')], max_length=16),
        ),
    ]
