# Generated by Django 5.2.17 on 2026-09-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planchangerequest',
            name='kind',
            field=models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('addon', 'Add units'), ('addon_remove', 'Remove units'), ('switch', 'Change of currency')], max_length=16),
        ),
    ]
