# Generated by Django 5.2.17 on 2026-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_plan_change_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
