# Generated by Django 5.2.17 on 2026-09-27 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_owner_tenant_controls'),
        ('org', '0017_company_is_demo'),
        ('subscriptions', '0008_payment_transfer_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status_before_suspension',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='suspension_kind',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('unpaid', 'Until payment')], max_length=16),
        ),
        migrations.CreateModel(
            name='CompanyDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ref', models.PositiveBigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('restored', 'Restored'), ('purged', 'Purged')], default='scheduled', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('purge_after', models.DateTimeField()),
                ('subscription_status', models.CharField(blank=True, max_length=16)),
                ('backup_rows', models.PositiveIntegerField(default=0)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('purged_rows', models.JSONField(blank=True, default=dict)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ops.backuprecord')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions', to='org.company')),
                ('purged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('company',), name='one_scheduled_deletion_per_company')],
            },
        ),
    ]
