# Generated by Django 5.0.14 on 2026-09-12 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("organisation_name", models.CharField(blank=True, max_length=255)),
                (
                    "deployment_mode",
                    models.CharField(
                        default="standalone", editable=False, max_length=16
                    ),
                ),
                ("application_version", models.CharField(blank=True, max_length=40)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LicenseActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_id", models.UUIDField(unique=True)),
                ("organisation_name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("perpetual", "Perpetual"), ("term", "Fixed term")],
                        max_length=16,
                    ),
                ),
                ("key_id", models.CharField(max_length=64)),
                ("modules", models.JSONField(default=list)),
                ("limits", models.JSONField(default=dict)),
                ("usable_until", models.DateTimeField(blank=True, null=True)),
                ("grace_until", models.DateTimeField(blank=True, null=True)),
                ("maintenance_until", models.DateField(blank=True, null=True)),
                (
                    "max_application_version",
                    models.CharField(blank=True, max_length=40),
                ),
                ("payload", models.JSONField()),
                ("signature", models.TextField()),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activations",
                        to="licensing.installation",
                    ),
                ),
            ],
            options={
                "ordering": ["-activated_at"],
            },
        ),
    ]
