# Generated by Django 5.0.14 on 2026-09-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="singleton_key",
            field=models.PositiveSmallIntegerField(
                default=1, editable=False, unique=True
            ),
        ),
    ]
