# Generated by Django 5.0.14 on 2026-09-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_installation_singleton_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='previous_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='installation',
            name='upgraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
