# Generated by Django 5.0.14 on 2026-09-11 22:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leaverequest_medical_report_position_base_salary_and_more'),
        ('org', '0007_storemodeaccessexception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the payroll month')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='org.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('position_title', models.CharField(blank=True, max_length=255)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('advances_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['employee_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'period'), name='uniq_payroll_run_per_month'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='uniq_payroll_entry_per_employee'),
        ),
    ]
