# Generated by Django 5.0.14 on 2026-09-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_payrollrun_payrollentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
