# Generated by Django 5.0.14 on 2026-09-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_attendance_source_leave_alter_leaverequest_status'),
        ('org', '0007_storemodeaccessexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('casual', 'Casual'), ('unpaid', 'Unpaid'), ('sick', 'Sick'), ('other', 'Other')], max_length=16)),
                ('entitled_days', models.DecimalField(decimal_places=2, max_digits=7)),
                ('carried_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('note', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_allowances', to='hr.employee')),
            ],
            options={
                'ordering': ['-year', 'employee__full_name', 'leave_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='leaveallowance',
            constraint=models.UniqueConstraint(fields=('company', 'employee', 'year', 'leave_type'), name='unique_employee_leave_allowance'),
        ),
    ]
