# Generated by Django 5.0.14 on 2026-09-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_leaveallowance_and_more'),
        ('org', '0007_storemodeaccessexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAccrualPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('casual', 'Casual'), ('unpaid', 'Unpaid'), ('sick', 'Sick'), ('other', 'Other')], max_length=16)),
                ('annual_days', models.DecimalField(decimal_places=2, max_digits=7)),
                ('minimum_service_months', models.PositiveSmallIntegerField(default=0)),
                ('prorate_first_year', models.BooleanField(default=True)),
                ('carryover_limit', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.company')),
            ],
            options={
                'ordering': ['leave_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='leaveaccrualpolicy',
            constraint=models.UniqueConstraint(fields=('company', 'leave_type'), name='unique_company_leave_accrual_policy'),
        ),
    ]
