# Generated by Django 5.2.17 on 2026-09-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_leaveaccrualpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
