# Generated by Django 5.2.17 on 2026-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_attendance_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='absent_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='advances_recovered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='days_employed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='unpaid_leave_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='recover_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
