# Generated by Django 5.0.14 on 2026-07-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_taxprofile_gulf_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
