# Generated by Django 5.0.14 on 2026-07-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_company_address_company_email_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('shop', 'Single shop'), ('enterprise', 'Multi-branch business')], default='enterprise', max_length=16),
        ),
    ]
