# Generated by Django 5.0.14 on 2026-07-27 15:39

from django.db import migrations, models


def mark_existing_as_chosen(apps, schema_editor):
    """
    Companies that predate this field have been trading in whatever layout they
    had, so that layout is a settled decision — not an unanswered question.
    Leaving them at False would greet every existing owner with a setup prompt
    for something they never asked about.
    """
    Company = apps.get_model("org", "Company")
    Company.objects.update(business_type_chosen=True)


def unmark(apps, schema_editor):
    # Reversing the field's addition drops the column anyway; this exists so the
    # migration is not one-way.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_company_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_as_chosen, unmark),
    ]
