# Generated by Django 5.0.14 on 2026-09-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_groups"),
        ("org", "0006_company_business_type_chosen"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreModeAccessException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="store_mode_exceptions", to="org.company")),
                ("role", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="store_mode_exceptions", to="accounts.role")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="store_mode_exceptions", to="accounts.user")),
            ],
        ),
        migrations.AddConstraint(
            model_name="storemodeaccessexception",
            constraint=models.CheckConstraint(
                check=models.Q(("role__isnull", True), ("user__isnull", False)) | models.Q(("role__isnull", False), ("user__isnull", True)),
                name="store_mode_exception_exactly_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="storemodeaccessexception",
            constraint=models.UniqueConstraint(condition=models.Q(("user__isnull", False)), fields=("company", "user"), name="uniq_store_mode_exception_user"),
        ),
        migrations.AddConstraint(
            model_name="storemodeaccessexception",
            constraint=models.UniqueConstraint(condition=models.Q(("role__isnull", False)), fields=("company", "role"), name="uniq_store_mode_exception_role"),
        ),
    ]
