# Generated by Django 5.2.17 on 2026-09-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_storemodeaccessexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='Africa/Khartoum', max_length=64),
        ),
    ]
