# Generated by Django 5.2.17 on 2026-09-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_company_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stock_adjustment_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
