# Generated by Django 5.2.17 on 2026-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_costing_integrity_and_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_payment_terms_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
