# Generated by Django 5.2.17 on 2026-09-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_inflation_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='receipt_footer',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='company',
            name='receipt_paper',
            field=models.CharField(choices=[('a4', 'A4'), ('80mm', '80 mm roll'), ('58mm', '58 mm roll')], default='a4', max_length=8),
        ),
    ]
