# Generated by Django 5.2.17 on 2026-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_receipt_printing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='receipt_paper',
            field=models.CharField(choices=[('a4', 'A4'), ('a5', 'A5'), ('80mm', '80 mm roll'), ('58mm', '58 mm roll')], default='a4', max_length=8),
        ),
    ]
