# Generated by Django 5.2.17 on 2026-09-24 16:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_receipt_paper_a5'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10'), max_digits=5, null=True),
        ),
    ]
