# Generated by Django 5.2.17 on 2026-09-24 17:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_current_rates(apps, schema_editor):
    """Each company's rate today is the first known one. Older history is
    unknown, and is assumed to be that rate (see tax_rate_was_in_effect)."""
    TaxProfile = apps.get_model("org", "TaxProfile")
    TaxRateChange = apps.get_model("org", "TaxRateChange")
    TaxRateChange.objects.bulk_create(
        [
            TaxRateChange(company_id=company_id, rate=rate)
            for company_id, rate in TaxProfile.objects.values_list("company_id", "flat_tax_rate")
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_receipt_paper_a5'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rate_changes', to='org.company')),
            ],
            options={
                'ordering': ['company', '-effective_from', '-pk'],
            },
        ),
        migrations.RunPython(seed_current_rates, migrations.RunPython.noop),
    ]
