# Generated by Django 5.2.17 on 2026-09-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0017_company_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='contact_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
