# Generated by Django 5.2.17 on 2026-09-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0013_receipt_printing'),
        ('sales', '0019_bank_app_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=32, unique=True)),
                ('waba_id', models.CharField(blank=True, max_length=32)),
                ('display_phone', models.CharField(blank=True, max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('access_token', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text="Empty for the platform's own number.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to='org.company')),
            ],
            options={
                'ordering': ['display_phone'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('messages', models.PositiveSmallIntegerField(default=0)),
                ('statuses', models.PositiveSmallIntegerField(default=0)),
                ('unknown_numbers', models.PositiveSmallIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='whatsapp.whatsappaccount')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('wa_message_id', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('message_type', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='received', max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('error_title', models.CharField(blank=True, max_length=255)),
                ('wa_timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='org.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='sales.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='wa_msg_co_created_idx'), models.Index(fields=['account', 'phone'], name='wa_msg_acct_phone_idx')],
            },
        ),
    ]
