# Generated by Django 5.2.17 on 2026-09-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_receipt_printing'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('invoice_sent', 'Invoice after a sale'), ('payment_received', 'Payment received'), ('debt_reminder', 'Debt reminder'), ('order_confirmed', 'Public order confirmed')], max_length=32)),
                ('template_name', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(default='ar', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='org.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'purpose'), name='uniq_wa_template_purpose')],
            },
        ),
    ]
