# Generated by Django 5.2.17 on 2026-09-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget_budgetline_and_more'),
        ('hr', '0007_leaveaccrualpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payroll_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='hr.payrollrun'),
        ),
        migrations.AddField(
            model_name='expense',
            name='salary_advance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='hr.salaryadvance'),
        ),
    ]
