# Generated by Django 5.2.17 on 2026-09-23 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_payroll_run_expense_salary_advance'),
        ('sales', '0024_cashshift_expected_at_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='drawer_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='sales.cashdrawermovement'),
        ),
    ]
