# Generated by Django 5.2.17 on 2026-09-24 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_drawer_movement'),
        ('sales', '0024_cashshift_expected_at_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='company_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='sales.companybankaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='finance.expense'),
        ),
    ]
