# Generated by Django 5.0.14 on 2026-07-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_uniq_product_barcode_per_company'),
        ('org', '0002_taxprofile_gulf_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_sequence', to='org.company')),
            ],
        ),
    ]
