# Generated by Django 5.0.14 on 2026-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_barcodesequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stock_tracked',
            field=models.BooleanField(default=True),
        ),
    ]
