# Generated by Django 5.0.14 on 2026-09-14 13:18

import django.utils.timezone
from django.db import migrations, models


def backfill_received_at(apps, schema_editor):
    """Existing rows were written by the server at their business time; the audit stamp is the same instant."""
    apps.get_model("inventory", "StockMovement").objects.filter(received_at__isnull=True).update(received_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_is_stock_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_received_at, migrations.RunPython.noop),
    ]
