# Generated by Django 5.0.14 on 2026-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_business_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
