# Generated by Django 5.0.14 on 2026-09-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stock_count'),
        ('org', '0007_storemodeaccessexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('barcode', models.CharField(blank=True, max_length=128)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packs', to='org.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='inventory.product')),
            ],
            options={
                'ordering': ['product', 'quantity'],
            },
        ),
        migrations.AddConstraint(
            model_name='productpack',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_pack_name_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productpack',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('company', 'barcode'), name='uniq_pack_barcode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='productpack',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='pack_quantity_positive'),
        ),
    ]
