# Generated by Django 5.2.17 on 2026-09-17 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_public_site_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reason_code',
            field=models.CharField(choices=[('count', 'Count correction'), ('damage', 'Damaged'), ('expiry', 'Expired'), ('theft', 'Theft / loss'), ('sample', 'Sample / internal use'), ('opening', 'Opening stock'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
