# Generated by Django 5.2.17 on 2026-09-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_hot_table_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
