# Generated by Django 5.2.17 on 2026-09-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_reference_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='counted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
