# Generated by Django 5.2.17 on 2026-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_free_archived_pack_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
