# Generated by Django 5.0.14 on 2026-07-24 09:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_due_date_invoice_payment_terms_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
    ]
