# Generated by Django 5.0.14 on 2026-09-14 13:18

import django.utils.timezone
from django.db import migrations, models


def backfill_received_at(apps, schema_editor):
    """Existing rows were written by the server at their business time; the audit stamp is the same instant."""
    apps.get_model("sales", "Invoice").objects.filter(received_at__isnull=True).update(received_at=models.F("issued_at"))
    apps.get_model("sales", "Payment").objects.filter(received_at__isnull=True).update(received_at=models.F("recorded_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_invoice_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_received_at, migrations.RunPython.noop),
    ]
