# Generated by Django 5.0.14 on 2026-09-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_business_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='local_reference',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
    ]
