# Generated by Django 5.0.14 on 2026-09-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_invoice_local_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
