# Generated by Django 5.0.14 on 2026-09-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_packs'),
        ('sales', '0008_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.productpack'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='pack_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='pack_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='packs_sold',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
    ]
