# Generated by Django 5.2.17 on 2026-09-17 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_company_timezone'),
        ('returns', '0003_note_numbers'),
        ('sales', '0009_invoice_line_packs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=16)),
                ('reference_last4', models.CharField(blank=True, max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='org.company')),
                ('company_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.companybankaccount')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='returns.creditnote')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_recorded', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.cashshift')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='cashdrawermovement',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drawer_movements', to='sales.refund'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
    ]
