# Generated by Django 5.2.17 on 2026-09-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_refunds_and_credit_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
    ]
