# Generated by Django 5.2.17 on 2026-09-17 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_public_site_images'),
        ('org', '0008_company_timezone'),
        ('sales', '0011_costing_integrity_and_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('local_reference', ''), _negated=True), fields=('company', 'local_reference'), name='uniq_invoice_local_reference_per_company'),
        ),
    ]
