# Generated by Django 5.2.17 on 2026-09-17 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_hot_table_indexes'),
        ('org', '0009_costing_integrity_and_currency'),
        ('sales', '0012_offline_robustness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', '-issued_at'], name='invoice_co_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'due_date'], name='invoice_co_due_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'customer'], name='invoice_co_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'received_at'], name='invoice_co_received_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['product', 'invoice'], name='invoiceline_product_inv_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', '-recorded_at'], name='payment_co_recorded_idx'),
        ),
    ]
