# Generated by Django 5.2.17 on 2026-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_hot_table_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
