# Generated by Django 5.2.17 on 2026-09-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_backfill_due_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
