# Generated by Django 5.2.17 on 2026-09-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_costing_integrity_and_currency'),
        ('sales', '0016_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='returns.creditnote'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Store credit')], max_length=16),
        ),
    ]
