# Generated by Django 5.2.17 on 2026-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_payment_store_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankaccount',
            name='show_to_customers',
            field=models.BooleanField(default=False),
        ),
    ]
