# Generated by Django 5.2.17 on 2026-09-19 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_device'),
        ('returns', '0004_costing_integrity_and_currency'),
        ('sales', '0018_bank_account_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankaccount',
            name='channel',
            field=models.CharField(choices=[('bank', 'Bank account'), ('bankak', 'Bankak'), ('fawri', 'Fawri'), ('ocash', 'O-Cash'), ('wallet', 'Other mobile wallet')], default='bank', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company_bank_account', 'transfer_reference'], name='payment_acct_ref_idx'),
        ),
    ]
