# Generated by Django 5.2.17 on 2026-09-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_bank_app_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
