# Generated by Django 5.2.17 on 2026-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_whatsapp_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
