# Generated by Django 5.2.17 on 2026-09-20 20:27

from django.conf import settings
from django.db import migrations, models


def blank_duplicate_references(apps, schema_editor):
    Payment = apps.get_model("sales", "Payment")
    seen = set()
    for payment in (
        Payment.objects.exclude(transfer_reference="")
        .order_by("recorded_at", "pk")
        .only("pk", "company_bank_account_id", "transfer_reference", "invoice_id")
    ):
        key = (payment.company_bank_account_id, payment.transfer_reference, payment.invoice_id)
        if key in seen:
            Payment.objects.filter(pk=payment.pk).update(transfer_reference="")
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_receipt_printing'),
        ('returns', '0004_costing_integrity_and_currency'),
        ('sales', '0021_payment_receipt_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Data recorded before this constraint may already hold the same
        # reference twice on one invoice (the race this constraint closes).
        # Keep the first row's reference; later copies keep their last-4 for
        # the receipt but drop the full id so the constraint can be created.
        migrations.RunPython(blank_duplicate_references, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('transfer_reference', ''), _negated=True), fields=('company_bank_account', 'transfer_reference', 'invoice'), name='uniq_payment_reference_per_invoice'),
        ),
    ]
