# Generated by Django 5.2.17 on 2026-09-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_payment_reference_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='whatsapp_opt_in',
        ),
    ]
