# Generated by Django 5.2.17 on 2026-09-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_remove_customer_whatsapp_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='expected_at_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
