# Generated by Django 5.2.17 on 2026-09-28 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_adjustment_transfer_received_at'),
        ('org', '0017_company_is_demo'),
        ('sales', '0026_price_rule_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'updated_at'], name='invoice_co_updated_idx'),
        ),
    ]
