# Generated by Django 5.2.17 on 2026-09-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_invoice_updated_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_body_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
