# Generated by Django 5.2.17 on 2026-09-17 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_company_timezone'),
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('client_uuid', models.UUIDField()),
                ('op_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='syncoperation',
            constraint=models.UniqueConstraint(fields=('batch', 'index'), name='uniq_sync_op_per_slot'),
        ),
        migrations.AddField(
            model_name='discardedoperation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_operations', to='org.branch'),
        ),
        migrations.AddField(
            model_name='discardedoperation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discarded_operations', to='org.company'),
        ),
        migrations.AddField(
            model_name='discardedoperation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_operations_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discardedoperation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='discardedoperation',
            constraint=models.UniqueConstraint(fields=('company', 'client_uuid'), name='uniq_discarded_op_per_company'),
        ),
    ]
