# Generated by Django 5.2.17 on 2026-09-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_offline_robustness'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncoperation',
            name='error_field',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
