# Generated by Django 5.2.17 on 2026-09-17 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scrub_credentials_from_activity_log'),
        ('org', '0009_costing_integrity_and_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['company', '-created_at'], name='actlog_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='actlog_user_created_idx'),
        ),
    ]
