# Generated by Django 5.2.17 on 2026-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hot_table_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=128)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', '-created_at'], name='actlogarc_company_created_idx')],
            },
        ),
    ]
