# Generated by Django 5.2.17 on 2026-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activitylogarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=32, unique=True)),
                ('exc_type', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('path', models.CharField(max_length=300)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('traceback', models.TextField(blank=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['resolved_at', '-last_seen'], name='error_open_recent_idx')],
            },
        ),
    ]
