# Generated by Django 5.2.17 on 2026-09-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_backuprecord_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='payload_gz',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
