# Generated by Django 5.2.17 on 2026-09-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_backuprecord_payload_gz'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='keep_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('restore', 'Restore'), ('deletion', 'Company deletion')], max_length=16),
        ),
    ]
